<a href="https://colab.research.google.com/github/19PA1A0548/courseera/blob/master/Untitled51.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

In [0]:
df=pd.read_csv("/content/Energy Census and Economic Data US 2010-2014.csv")
df.head()

  StateCodes       State  Region  ...  RNETMIG2012  RNETMIG2013  RNETMIG2014
0         AL     Alabama     3.0  ...     1.001333     1.562247     1.577963
1         AK      Alaska     4.0  ...     1.835376    -0.585695   -10.884734
2         AZ     Arizona     4.0  ...     0.621971     0.509473    -0.221767
3         AR    Arkansas     3.0  ...     7.155212     6.052353     8.410441
4         CA  California     4.0  ...     2.772770     2.866127     3.346406

[5 rows x 192 columns]

In [0]:
df.shape

(52, 192)

In [0]:
df1=df[df["Region"]<4]
df1.head()

  StateCodes        State  Region  ...  RNETMIG2012  RNETMIG2013  RNETMIG2014
0         AL      Alabama     3.0  ...     1.001333     1.562247     1.577963
3         AR     Arkansas     3.0  ...     7.155212     6.052353     8.410441
6         CT  Connecticut     1.0  ...    -1.059166     0.021964    -2.555302
7         DE     Delaware     3.0  ...     6.221263     6.006120     7.713663
8         FL      Florida     3.0  ...    10.722573    10.702501    12.703423

[5 rows x 192 columns]

In [0]:
df=df.iloc[0:,0:5]
df.head()

  StateCodes       State  Region  Division  Coast
0         AL     Alabama     3.0       6.0    1.0
1         AK      Alaska     4.0       9.0    1.0
2         AZ     Arizona     4.0       8.0    0.0
3         AR    Arkansas     3.0       7.0    0.0
4         CA  California     4.0       9.0    1.0